# Generated by Django 3.1 on 2020-08-31 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecontent',
            options={'ordering': ('-Rec_conModify',), 'verbose_name': 'recipe_post'},
        ),
        migrations.AlterField(
            model_name='youtubecontent',
            name='You_conMemID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='OWNER'),
        ),
    ]
