# Generated by Django 3.1 on 2020-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecontent',
            name='Rec_conModify',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE'),
        ),
    ]
