# Generated by Django 3.1 on 2020-08-14 14:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200814_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubecontent',
            name='You_conContent',
            field=tinymce.models.HTMLField(verbose_name='CONTENT'),
        ),
    ]
