# Generated by Django 3.1 on 2020-09-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200831_1526'),
        ('recipe', '0002_auto_20200829_1540'),
    ]

    operations = [
    ]
