# Generated by Django 3.1 on 2020-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200814_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubecontent',
            name='You_conModify',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE'),
        ),
    ]
