# Generated by Django 3.1 on 2020-08-17 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0006_recipecontent_rec_conlikesuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecontent',
            name='Rec_conLikesUser',
            field=models.ManyToManyField(blank=True, related_name='Rec_conLikesUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
