# Generated by Django 3.1 on 2020-08-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotplace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='HOT_ID')),
                ('title', models.CharField(max_length=100, verbose_name='HOT_TITLE')),
                ('slug', models.SlugField(allow_unicode=True, help_text='one word for title alias.', unique=True, verbose_name='SLUG')),
                ('name', models.CharField(max_length=15, verbose_name='HOT_NAME')),
                ('content', models.TextField(verbose_name='HOT_CONTENT')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='HOT_CREATE_DATE')),
                ('modify_dt', models.DateTimeField(verbose_name='HOT_MODIFY_DATE')),
            ],
            options={
                'verbose_name': 'hotplace',
                'verbose_name_plural': 'hotplaces',
                'ordering': ('-modify_dt',),
            },
        ),
    ]
