# Generated by Django 3.1 on 2020-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='content',
            field=models.TextField(verbose_name='CONTENT'),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CREATE_DATE'),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='modify_dt',
            field=models.DateTimeField(verbose_name='MODIFY_DATE'),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='name',
            field=models.CharField(max_length=15, verbose_name='NAME'),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='title',
            field=models.CharField(max_length=100, verbose_name='TITLE'),
        ),
    ]
