# Generated by Django 3.1 on 2020-08-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplace',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
