# Generated by Django 3.1 on 2020-08-13 10:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('hotplace', '0003_auto_20200812_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplace',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
