# Generated by Django 3.1 on 2020-08-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0005_hotplace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='MODIFY_DATE'),
        ),
        migrations.CreateModel(
            name='HotplaceAttachFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('content_type', models.CharField(max_length=128, null=True, verbose_name='MIME TYPE')),
                ('size', models.IntegerField(verbose_name='파일 크기')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hotplace.hotplace', verbose_name='Hotplace')),
            ],
        ),
    ]
