# Generated by Django 3.1 on 2020-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0006_auto_20200814_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplace',
            name='coordinate',
            field=models.FloatField(blank=True, null=True, verbose_name='COORDINATE'),
        ),
        migrations.AlterField(
            model_name='hotplace',
            name='title',
            field=models.CharField(help_text='제목을 입력하세요', max_length=30, verbose_name='TITLE'),
        ),
    ]
