# Generated by Django 3.1 on 2020-08-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0007_auto_20200819_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotplace',
            name='coordinate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='COORDINATE'),
        ),
    ]
