# Generated by Django 3.1 on 2020-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotplace', '0008_auto_20200820_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='LATITUDE'),
        ),
        migrations.AddField(
            model_name='hotplace',
            name='longtitude',
            field=models.FloatField(blank=True, null=True, verbose_name='LONGTITUDE'),
        ),
    ]
