# Generated by Django 3.1 on 2020-08-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True, max_length=500, verbose_name='소개'),
        ),
    ]
